dist: xenial
sudo: required
language: cpp
compiler:
  - gcc
os: 
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   sudo add-apt-repository 'deb [arch=amd64] https://mirror.mxe.cc/repos/apt xenial main'  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   sudo apt-get -qq update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   sudo apt-get install -y texlive-binaries texlive-metapost libproj-dev libwxgtk3.0-dev libvtk6-dev survex imagemagick ghostscript libsqlite3-tcl    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   sudo apt-get install -y mxe-i686-w64-mingw32.static-binutils mxe-i686-w64-mingw32.static-bzip2 mxe-i686-w64-mingw32.static-expat mxe-i686-w64-mingw32.static-freetype-bootstrap mxe-i686-w64-mingw32.static-gcc mxe-i686-w64-mingw32.static-gettext mxe-i686-w64-mingw32.static-glib mxe-i686-w64-mingw32.static-harfbuzz mxe-i686-w64-mingw32.static-jpeg mxe-i686-w64-mingw32.static-libiconv mxe-i686-w64-mingw32.static-libpng mxe-i686-w64-mingw32.static-tiff mxe-i686-w64-mingw32.static-vtk mxe-i686-w64-mingw32.static-wxwidgets mxe-i686-w64-mingw32.static-xz mxe-i686-w64-mingw32.static-zlib mxe-i686-w64-mingw32.static-proj      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then   brew update                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then   brew tap homebrew/core          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then   brew unlink python@2            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then   brew install freetype wxmac vtk ; fi
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   export PATH=/usr/lib/mxe/usr/bin:$PATH   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   sudo sed -i '/pattern="PDF"/d' /etc/ImageMagick-6/policy.xml ; fi   # turn off policy preventing PDF conversion
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make config-debian              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   ./therion --print-symbols       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make samples                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make library                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make cleanrest                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make config-win32cross          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then   make config-macosx              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then   make ./therion                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then   make loch/loch                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then   ./therion --version             ; fi
branches:
  only:
    - master
